site_name: BigPoint RP | Wet en regelgeving
site_description: 'Wet en regelgeving van BigPoint'
nav:
  - Home: index.md
  - Server Regels: regels.md
  - Formeel Recht: wetboek.md

repo_url: https://github.com/mkdocs/mkdocs-bootswatch

  theme:
    name: flatly