site_name: BigPoint RP | Wet en regelgeving
site_description: 'Wet en regelgeving van BigPoint'
nav:
  - Home: index.md
  - Server Regels: regels.md
  - Formeel Recht: wetboek.md

theme:
    name: mkdocs
    locale: en
    custom_dir: my_theme_customizations/
    static_templates:
        - sitemap.html
    include_sidebar: false

plugins:
  - netlify-plugin-inline-critical-css
  - netlify-plugin-search-index
